[plugin]
repository = "https://github.com/QLEDHDTV/PhlegmaDilemma.git"
commit = "d99387591efc8a962e5aed8ff0c7c9149562201b"
owners = ["QLEDHDTV"]
project_path = "PhlegmaDilemma"
changelog = "Initial release (0.2.0.0)"
