[plugin]
repository = "https://github.com/QLEDHDTV/PhlegmaDilemma.git"
commit = "1692cb83e204a10f3ab0fe7739f9cc31e3a30c75"
owners = ["QLEDHDTV"]
project_path = "PhlegmaDilemma"
changelog = "Initial release (0.2.1.0)"
